list1=['Surat','Vyara','Vadodara','Ahmedabad','Div']
print("List1: ",list1)
list1.append('Bhuj')
print("\nAppend a new city name to the List: \n",list1)
list1.insert(3,'Tapi')
print("\nInsert a city name at 4th index position: \n",list1)
list1.sort()
print("\nSort the list and print all elements: \n",list1)
list1.reverse()
print("\nSort the elements of the list in descending order.: \n",list1)
print("\ndelete last three elements using pop operation:\n")
list1.pop()
list1.pop()
list1.pop()
print(list1)
